# -*- coding: utf-8 -*-
"""app.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kDPs6MAEdHijaNtwKEbFYQGf3JxbjZfx
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import yfinance as yf
# import pandas as pd
# from whatsapp_api_client_python import API
# from concurrent.futures import ThreadPoolExecutor
# import datetime
# import pytz
# import os
# 
# # --- CONFIGURACIÓN ESTÉTICA ---
# st.set_page_config(page_title="Top 6 Momentum", layout="wide", page_icon="📊")
# 
# st.markdown("""
#     <style>
#     .ticker-card {
#         background-color: #ffffff;
#         border: 1px solid #e6e9ef;
#         border-radius: 10px;
#         padding: 20px;
#         margin-bottom: 20px;
#         box-shadow: 2px 2px 5px rgba(0,0,0,0.05);
#         color: #1f1f1f;
#     }
#     .main { background-color: #f8f9fa; }
#     h3 { margin-top: 0; color: #007bff; }
#     </style>
#     """, unsafe_allow_html=True)
# 
# # --- RUTA PARA LA NUBE ---
# # Buscamos el archivo en la raíz del repositorio de GitHub
# RUTA_CSV = "ACTIVOS_BULLMARKET_USA.csv"
# 
# st.title("📈 Dashboard Top 6 Momentum")
# st.write("Análisis de tendencia y volumen - USA Market")
# 
# with st.sidebar:
#     st.header("⚙️ Configuración")
#     p_min = st.number_input("Precio Mín ($)", 0.01, 1000.0, 0.50)
#     p_max = st.number_input("Precio Máx ($)", 0.01, 1000.0, 17.0)
#     gap_min = st.slider("GAP Mínimo (%)", 0.0, 20.0, 2.0)
#     st.divider()
#     id_ins = st.text_input("ID Instancia", "7103533853")
#     token_ins = st.text_input("Token API", "e5f6764f996d4c9ea88594a98ebd1741f6ab9f8502a24687b5", type="password")
#     celular = st.text_input("WhatsApp", "5492664300161")
# 
# def obtener_datos_completos(ticker_raw):
#     try:
#         ticker = str(ticker_raw).split('.')[0].strip().upper()
#         stock = yf.Ticker(ticker)
#         df = stock.history(period="1mo")
#         if len(df) < 11: return None
#         precio_actual = df['Close'].iloc[-1]
#         cierre_ayer = df['Close'].iloc[-2]
#         gap = ((precio_actual - cierre_ayer) / cierre_ayer) * 100
#         if not (p_min <= precio_actual <= p_max) or gap < gap_min:
#             return None
#         vol_promedio_10d = df['Volume'].iloc[-11:-1].mean()
#         vol_hoy = df['Volume'].iloc[-1]
#         vol_rel = vol_hoy / vol_promedio_10d if vol_promedio_10d > 0 else 0
#         return {
#             "Ticker": ticker,
#             "Precio": round(precio_actual, 2),
#             "GAP %": round(gap, 2),
#             "Vol_Rel": round(vol_rel, 2),
#             "Hist": df['Close'],
#             "SL": round(precio_actual * 0.97, 2)
#         }
#     except: return None
# 
# if os.path.exists(RUTA_CSV):
#     tickers_lista = pd.read_csv(RUTA_CSV)['Ticker'].dropna().unique().tolist()
#     st.sidebar.success(f"📂 {len(tickers_lista)} Activos listos")
# else:
#     st.error("⚠️ Sube el archivo 'ACTIVOS_BULLMARKET_USA.csv' a tu GitHub.")
#     tickers_lista = []
# 
# if st.button("🔍 ANALIZAR Y ENVIAR"):
#     if tickers_lista:
#         with st.spinner("Procesando..."):
#             with ThreadPoolExecutor(max_workers=15) as executor: # Bajamos un poco los workers para la nube
#                 resultados = [r for r in list(executor.map(obtener_datos_completos, tickers_lista)) if r is not None]
#             if resultados:
#                 top_6 = sorted(resultados, key=lambda x: x['GAP %'], reverse=True)[:6]
#                 cols = st.columns(2)
#                 for i, res in enumerate(top_6):
#                     with cols[i % 2]:
#                         st.markdown(f"""<div class="ticker-card"><h3>🚀 {res['Ticker']}</h3><p><b>Precio:</b> ${res['Precio']} | <b>GAP:</b> +{res['GAP %']}%</p><p><b>Vol. Relativo:</b> {res['Vol_Rel']}x | <b>SL:</b> ${res['SL']}</p></div>""", unsafe_allow_html=True)
#                         st.line_chart(res['Hist'], height=180)
#                 ahora = datetime.datetime.now(pytz.timezone('America/Argentina/Buenos_Aires'))
#                 msg = f"🔔 *TOP 6 TENDENCIAS* ({ahora.strftime('%H:%M')})\n━━━━━━━━━━━━━━━━━━\n"
#                 for r in top_6:
#                     v_emoji = "🔥" if r['Vol_Rel'] > 1.2 else "📊"
#                     msg += f"📈 *{r['Ticker']}* | ${r['Precio']} | +{r['GAP %']}% | {v_emoji} {r['Vol_Rel']}x\n"
#                 try:
#                     greenAPI = API.GreenApi(id_ins, token_ins)
#                     greenAPI.sending.sendMessage(f"{celular}@c.us", msg)
#                     st.success("📱 Enviado.")
#                 except: st.error("Error WhatsApp.")